version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fastapi-sam-app"
s3_prefix = "fastapi-sam-app"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
resolve_s3 = true
